### ISSUE TITLE
Missing sufficient documentation

### ISSUE THREAD

**Issue by RobSmyth** [guibranco/MSBuild.Version.Target#1]
The project's `readme.md` needs more substance so that developers can recognise this project as being useful.

What is missing:

- Description of how the tool determines what is a `release configuration build`. 
- Scenarios
  - Push on a dev branch
  - Update version
  - Merge to a release branch

**Comment by guibranco** [comment]
I'll provide this soon!

**Comment by guibranco** [comment]
@RobSmyth  the scenarios can't be provided because this tool is about MSBuild and not a Git repository properly, so your request is invalid, if I understand well! If no, please, provide more details about it!

**Comment by guibranco** [comment]
Close #1
